In [65]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
data1 = pd.read_excel('StrawberryOrganizedScaled.xlsx')

In [69]:
data1 = pd.read_excel('TomatoesTarget_CO2.xlsx')
data1

,Total Weight,Fruit Number,Fruit Fresh Weight (3),Brix,Truss Weight,Total Fruit Weight,Fruit Dry Weight (3),D/F,Total DW,Individual Fruit Weight,Red fruit weight,FW:DW,Drymatter%
0,1524.32,181,527.330,209.30,175.39,1345.69,53.99,2.513363,139.992065,176.783433,175.776667,235.189955,251.336306
1,1519.75,155,569.710,205.30,233.72,1284.78,58.94,2.501407,134.170498,200.213509,189.903333,233.802497,250.140742
2,1919.16,193,644.538,240.10,265.00,1657.04,67.18,2.544295,171.842922,208.336495,214.846000,230.945481,254.429464
3,1955.29,204,611.110,254.90,325.46,1635.55,58.01,2.342552,155.447845,194.233020,203.703333,251.777546,234.255198
4,2686.77,294,832.540,239.85,455.50,2233.90,88.96,2.663279,237.669330,181.562520,277.513333,225.363908,266.327933
5,1532.85,188,496.450,235.80,316.83,1210.60,57.78,2.878675,140.531929,156.787119,165.483333,203.599968,287.867464
6,1116.37,180,425.650,230.35,294.18,825.92,46.48,2.609292,90.949157,111.287315,141.883333,224.298794,260.929232
7,1037.11,172,356.040,227.75,214.77,826.36,42.27,2.692556,96.904776,105.435400,118.680000,198.821513,269.255595
8,1004.59,196,311.460,238.55,154.49,846.18,33.58,2.385349,90.430393,94.945798,103.820000,206.684925,238.534941
9,868.63,162,279.530,161.30,119.28,748.78,31.53,2.007103,83.526071,77.007472,93.176667,147.407085,200.710325

In [71]:
data1 = data1.cumsum()
data1

,Total Weight,Fruit Number,Fruit Fresh Weight (3),Brix,Truss Weight,Total Fruit Weight,Fruit Dry Weight (3),D/F,Total DW,Individual Fruit Weight,Red fruit weight,FW:DW,Drymatter%
0,1524.32,181,527.330,209.30,175.39,1345.69,53.99,2.513363,139.992065,176.783433,175.776667,235.189955,251.336306
1,3044.07,336,1097.040,414.60,409.11,2630.47,112.93,5.014770,274.162563,376.996941,365.680000,468.992452,501.477048
2,4963.23,529,1741.578,654.70,674.11,4287.51,180.11,7.559065,446.005486,585.333437,580.526000,699.937933,755.906512
3,6918.52,733,2352.688,909.60,999.57,5923.06,238.12,9.901617,601.453331,779.566457,784.229333,951.715479,990.161710
4,9605.29,1027,3185.228,1149.45,1455.07,8156.96,327.08,12.564896,839.122661,961.128976,1061.742667,1177.079387,1256.489643
5,11138.14,1215,3681.678,1385.25,1771.90,9367.56,384.86,15.443571,979.654590,1117.916095,1227.226000,1380.679355,1544.357106
6,12254.51,1395,4107.328,1615.60,2066.08,10193.48,431.34,18.052863,1070.603747,1229.203410,1369.109333,1604.978149,1805.286339
7,13291.62,1567,4463.368,1843.35,2280.85,11019.84,473.61,20.745419,1167.508523,1334.638810,1487.789333,1803.799663,2074.541933
8,14296.21,1763,4774.828,2081.90,2435.34,11866.02,507.19,23.130769,1257.938917,1429.584607,1591.609333,2010.484587,2313.076875
9,15164.84,1925,5054.358,2243.20,2554.62,12614.80,538.72,25.137872,1341.464988,1506.592079,1684.786000,2157.891672,2513.787200

In [72]:
df_norm = (data1-data1.min())/(data1.max()-data1.min())
df_norm

,Total Weight,Fruit Number,Fruit Fresh Weight (3),Brix,Truss Weight,Total Fruit Weight,Fruit Dry Weight (3),D/F,Total DW,Individual Fruit Weight,Red fruit weight,FW:DW,Drymatter%
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.111414,0.088876,0.125846,0.100939,0.098233,0.114009,0.121593,0.110562,0.111672,0.150558,0.125846,0.121601,0.110562
2,0.252110,0.199541,0.268222,0.218988,0.209614,0.261052,0.260186,0.223019,0.254699,0.307225,0.268222,0.241716,0.223019
3,0.395454,0.316514,0.403213,0.344314,0.346406,0.406187,0.379861,0.326560,0.384080,0.453286,0.403213,0.372666,0.326560
4,0.592424,0.485092,0.587118,0.462240,0.537855,0.604420,0.563386,0.444276,0.581895,0.589818,0.587118,0.489878,0.444276
5,0.704799,0.592890,0.696781,0.578175,0.671020,0.711846,0.682586,0.571513,0.698861,0.707720,0.696781,0.595771,0.571513
6,0.786641,0.696101,0.790805,0.691430,0.794665,0.785137,0.778475,0.686844,0.774559,0.791407,0.790805,0.712429,0.686844
7,0.862672,0.794725,0.869453,0.803407,0.884933,0.858466,0.865678,0.805854,0.855214,0.870693,0.869453,0.815836,0.805854
8,0.936320,0.907110,0.938253,0.920694,0.949866,0.933555,0.934953,0.911286,0.930480,0.942091,0.938253,0.923333,0.911286
9,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [76]:
target = pd.read_csv('CornellStrawberryHarvestSumData.csv').drop('Harvest #', axis=1)
target = target.loc[target.index % 2 == 1] #0 is CO2 and 1 is Control
target = target.loc[target['Cultivar'] == 'CA']
target = target.drop('Treatment', axis=1).drop('Cultivar', axis=1)
target = target.cumsum()
target

      TB#     TBFW  Mean TBFW/Berry  MB#    MBFW  Mean MBFW/Berry
55     26    534.1        22.330476    7   162.3        24.330000
57     37    838.1        55.663810   12   364.3        64.380000
59     58   1077.6        66.098333   20   491.4        81.442500
61    111   1663.2        75.951515   41   872.9        98.580714
63    129   1771.1        82.849134   46   938.5       111.055714
65    184   2218.2        92.069829   64  1198.5       128.171905
67    241   2908.5       104.101440   84  1596.9       145.069312
69    293   3305.5       112.020606   90  1695.3       164.389312
71    333   3549.2       117.897360   98  1754.4       175.182646
73    381   4021.6       127.704438  109  1924.8       191.409729
75    457   4599.6       135.781250  125  2220.8       210.491210
77    540   5504.0       146.544296  152  2514.2       220.761766
79    623   6293.0       156.571624  182  2923.9       234.620251
81    717   7146.2       165.566280  223  3483.2       249.071766
83    765   7609.6       175.972492  239  3738.7       265.784729
85    832   8138.5       184.159089  259  4075.7       282.617136
87    925   9155.0       195.596514  305  4610.7       294.017434
89   1023  10209.6       206.444300  352  5366.3       310.168545
91   1117  11339.6       218.790055  404  5994.4       323.354716
93   1245  12348.7       226.390619  457  6718.9       336.944669
95   1373  13369.0       234.944401  512  7362.0       349.799491
97   1524  14273.2       241.126819  563  8024.1       361.775231
99   1626  14934.3       248.034971  593  8275.0       372.277374
101  1680  15465.1       257.341866  621  8645.0       384.614134
103  1724  15914.7       267.471032  643  8926.8       396.823800
105  1779  16370.3       276.051489  661  9142.8       408.379861
107  1825  16745.2       284.256813  673  9253.8       417.525694

In [77]:
target_norm = (target-target.min())/(target.max()-target.min())
target_norm

          TB#      TBFW  Mean TBFW/Berry       MB#      MBFW  Mean MBFW/Berry
55   0.000000  0.000000         0.000000  0.000000  0.000000         0.000000
57   0.006115  0.018753         0.127262  0.007508  0.022219         0.101858
59   0.017788  0.033526         0.167100  0.019520  0.036199         0.145252
61   0.047248  0.069650         0.204718  0.051051  0.078161         0.188839
63   0.057254  0.076306         0.231052  0.058559  0.085376         0.220566
65   0.087827  0.103886         0.266256  0.085586  0.113975         0.264097
67   0.119511  0.146468         0.312191  0.115616  0.157796         0.307072
69   0.148416  0.170957         0.342425  0.124625  0.168619         0.356208
71   0.170650  0.185990         0.364862  0.136637  0.175120         0.383658
73   0.197332  0.215130         0.402304  0.153153  0.193862         0.424928
75   0.239578  0.250785         0.433140  0.177177  0.226420         0.473457
77   0.285714  0.306574         0.474232  0.217718  0.258692         0.499578
79   0.331851  0.355244         0.512515  0.262763  0.303756         0.534823
81   0.384102  0.407875         0.546855  0.324324  0.365275         0.571577
83   0.410784  0.436460         0.586585  0.348348  0.393378         0.614083
85   0.448027  0.469086         0.617840  0.378378  0.430446         0.656892
87   0.499722  0.531790         0.661507  0.447447  0.489292         0.685886
89   0.554197  0.596844         0.702922  0.518018  0.572403         0.726963
91   0.606448  0.666549         0.750057  0.596096  0.641489         0.760498
93   0.677599  0.728797         0.779075  0.675676  0.721179         0.795061
95   0.748749  0.791735         0.811732  0.758258  0.791916         0.827754
97   0.832685  0.847512         0.835335  0.834835  0.864742         0.858212
99   0.889383  0.888293         0.861710  0.879880  0.892339         0.884922
101  0.919400  0.921036         0.897242  0.921922  0.933036         0.916297
103  0.943858  0.948770         0.935914  0.954955  0.964032         0.947350
105  0.974430  0.976874         0.968673  0.981982  0.987791         0.976740
107  1.000000  1.000000         1.000000  1.000000  1.000000         1.000000

In [78]:
target_norm.to_excel(r'C:\Users\shenyutao\Desktop\Summer2022\LESA\data\GH_Tomato\organized data\Strawberry_Target_CA.xlsx')